import os
from dotenv import load_dotenv

load_dotenv()

# Database
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
TEST_POSTGRES_DB = os.getenv("TEST_POSTGRES_DB")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = 5432

BASE_DATABASE_URL = (
    f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}"
)

DATABASE_URL = f"{BASE_DATABASE_URL}/{POSTGRES_DB}"
TEST_DATABASE_URL = f"{BASE_DATABASE_URL}/{TEST_POSTGRES_DB}"

# Auth
SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
REFRESH_TOKEN_EXPIRE_SECONDS = (
    int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS")) * 24 * 60 * 60
)

# Redis
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = 6379
REDIS_DB = os.getenv("REDIS_DB")
TEST_REDIS_DB = os.getenv("TEST_REDIS_DB")

REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")

BASE_REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"

REDIS_URL = f"{BASE_REDIS_URL}/{REDIS_DB}"
TEST_REDIS_URL = f"{BASE_REDIS_URL}/{TEST_REDIS_DB}"

CITIZEN_EXPIRE_SECONDS = int(os.getenv("CITIZEN_EXPIRE_DAYS")) * 24 * 60 * 60
