"""add citizens table and update meetings

Revision ID: f5ce9b71252e
Revises: 79797c188305
Create Date: 2025-08-11 12:27:01.084194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5ce9b71252e"
down_revision: Union[str, Sequence[str], None] = "79797c188305"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "citizens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("pin_code", sa.VARCHAR(length=7), nullable=False),
        sa.Column("patronymic", sa.VARCHAR(length=255), nullable=True),
        sa.Column("phone", sa.VARCHAR(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("meetings", sa.Column("citizen_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "meetings", "citizens", ["citizen_id"], ["id"])
    op.drop_column("meetings", "citizen_pin_code")
    op.drop_column("meetings", "citizen_phone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meetings",
        sa.Column(
            "citizen_phone", sa.VARCHAR(length=12), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "meetings",
        sa.Column(
            "citizen_pin_code",
            sa.VARCHAR(length=7),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "meetings", type_="foreignkey")
    op.drop_column("meetings", "citizen_id")
    op.drop_table("citizens")
    # ### end Alembic commands ###
